

export const incomeAndExpense = [
    "Admission",
    "Admission Form",
    "Annual Charge",
    "Audit Expenses",
    "Audit Fee",
    "Bank Charge",
    "Bank Interest",
    "Building (Repair)",
    "Computer (Repair)",
    "Computer Support",
    "Daily Allowance",
    "Donation Company",
    "Donation Government Agency",
    "Donation Invidual",
    "DropShip",
    "Electricity Bills",
    "Fuel",
    "Furniture (Repair)",
    "Interest On Borrowing",
    "Kitchen Gas",
    "Kitchen Groceries",
    "Kitchen Utensils",
    "Printing",
    "Promotion Expenses",
    "Rent",
    "Resale",
    "Salary",
    "Software",
    "Staff Training",
    "Stationary",
    "Telephone Bills",
    "Transportation (Fare)",
    "Transportation (Insurance)",
    "Transportation (Renewal)",
    "Transportation (Repair)",
    "Vehicle (Repair)",
    "Water Bills"
]
export const assets=[
    "RBB Acc No. 1001244226453",
    "NBL Acc No. 1001244343453",
    "SBL Acc No. 1001244228453",
    "Cash Balance",
    "P.T. Cash",
    "Account Recievable"
]
export const liabilities = [
    "Share Capital Archana",
    "Share Capital Sangita",
    "Borrowing Loan Bank",
    "Borrowing Archana Rimal",
    "Borrowing Sangeeta Neupane",
    "Borrowing Others",
    "Social Security Tax",
    "Salary Tax",
    "Salary Payable",
    "Audit Fee Payable",
    "Other Payable",
    "Capital Reserve/ Deficit"
]
export const headerCodes = {
    "0001":"Admission",
    "0002":"Admission Form",
    "0003":"Annual Charge",
    "0004":"Audit Expenses",
    "0005":"Audit Fee",
    "0006":"Bank Charge",
    "0007":"Bank Interest",
    "0008":"Building (Repair)",
    "0009":"Computer (Repair)",
    "0010":"Computer Support",
    "0011":"Daily Allowance",
    "0012":"Donation Company",
    "0013":"Donation Government Agency",
    "0014":"Donation Invidual",
    "0015":"DropShip",
    "0016":"Electricity Bills",
    "0017":"Fuel",
    "0018":"Furniture (Repair)",
    "0019":"Interest On Borrowing",
    "0020":"Kitchen Gas",
    "0021":"Kitchen Groceries",
    "0022":"Kitchen Utensils",
    "0023":"Printing",
    "0024":"Promotion Expenses",
    "0025":"Rent",
    "0026":"Resale",
    "0027":"Salary",
    "0028":"Software",
    "0029":"Staff Training",
    "0030":"Stationary",
    "0031":"Telephone Bills",
    "0032":"Transportation (Fare)",
    "0033":"Transportation (Insurance)",
    "0034":"Transportation (Renewal)",
    "0035":"Transportation (Repair)",
    "0036":"Vehicle (Repair)",
    "0038":"Water Bills",
}

